### ISSUE TITLE
The Maven repo URL is giving 404

### ISSUE THREAD

**Issue by renatoathaydes** [knopflerfish/www.knopflerfish.org#1]
Hi,

I am trying to use the Maven repo to get artifacts but it seems to be currently offline.

http://www.knopflerfish.org/maven2

I get 404 when I hit this.

**Comment by janste63** [comment]
Sorry for the delay. We are looking at how to handle maven.

**Comment by joergsesterhenn** [comment]
Is there any update on this? We want to use some other maven-plugin (https://docs.xebialabs.com/xldeploy-maven-plugin/5.1.x/usage.html) that relies on your repository.
Our Nexus repository can not download an Index nor Artifacts and visiting the page in a browser returns Error 404...

**Comment by chlarsson** [comment]
Cleaning up and closing old issues. This is fixed. If you still encounter problems please reopen the issue.

**Comment by renatoathaydes** [comment]
That's fine, I've tested and it works now. Thanks.
